### ISSUE TITLE
SuperMacro and CastModifier incompatibility

### ISSUE THREAD

**Issue by snawfu** [DennisWG/CastModifier#12]
When I have SuperMacro and CastModifier both running and I use any macro that has emote text or a channel message like /say /y /world etc; it prints 3 times for no reason.
CastModifier disabled, the problem is gone.

https://i.gyazo.com/94b0bb0f246b1d18c6abbc54af882b2c.png

screenshot of the issue for example

**Comment by SalviaSage** [comment]
I also have this bug. It prints the text 3 times when it should print it once.
Please fix this.

**Comment by DennisWG** [comment]
I can not reproduce this. What does your macro look like? Do you have any other Addons installed beside SuperMacro and CastModifier? Have you tried disabling all of them except those two?

**Comment by snawfu** [comment]
Macro is like any other

/s helo
/y helo
/1 helo
/2 helo
etc

It can also be a third addon that is interfering but it always stops when I disable CastModifier - will do more testing with individual addons.

**Comment by DennisWG** [comment]
Nevermind, I was able to reproduce this just now. I'll work on a fix ASAP.

**Comment by snawfu** [comment]
Thanks !

**Comment by DennisWG** [comment]
Fixed!
