### ISSUE TITLE
Error:  invalid control char near `char(0)'

### ISSUE THREAD

**Issue by SalviaSage** [DennisWG/CastModifier#13]
Error:  invalid control char near `char(0)'
AddOn: CastModifier
File: sRaidFrames.lua
Line: 1
Count: 1

This error exists with the latest version of CastModifier.

**Comment by DennisWG** [comment]
I can not reproduce this error. What client locale are you using? Have you modified the `sRaidFrames.lua` file in any way?

**Comment by SalviaSage** [comment]
You released an update since then, I downloaded it and deleted my WDB folder and there were no errors.
You can close this issue, false alarm.
