### ISSUE TITLE
Missing distinction on curses

### ISSUE THREAD

**Issue by Krisstal** [DennisWG/CastModifier#18]
After i wrote a Tab Targetting curse macro for different applications I came across the following problem:

The [nodebuff: cursexyz] conditional doesn't seem to differentiate between curses. 
So the check for the Curse of the Elements in the macro below passes eventhough a different curse is up on the target while Curse of the Elements isn't actually debuffed. 
Example: There are 4 mobs. 3 of them are debuffed with Curse of Recklessness while the 4th is not debuffed. Applying the macro will switch through the first 3 mobs without doing anything(as it is probably thinking the curse has already been applied) and only the 4th Mob will be debuffed as expected with Curse of the Elements. Macro below:

Main Macro:
/cast [nodebuff: Curse of the  Elements] Curse of the Elements; [debuff: Curse of the Elements] {m1}

Childmacro({m1})
/script TargetNearestEnemy()

//maybe i just did the syntax wrong but ive tested every segemtn of the macro indivdually and this is the conclusion Im coming to.

**Comment by DennisWG** [comment]
The wording in the [Wiki](https://github.com/DennisWG/CastModifier/wiki/Conditionals#nobuffname-nodebuffname-nomybuffname-nomydebuffname) was a little weird (I updated it now), but you need to replace white spaces with underscores '_'.

So `/cast [nodebuff:Curse of the Elements] Curse of the Elements` must be `/cast [nodebuff:Curse_of_the_Elements] Curse of the Elements`.
