### ISSUE TITLE
Possible? Check if skill is available

### ISSUE THREAD

**Issue by moootv** [DennisWG/CastModifier#20]
Great Addon!

Is there a way to check if a skill is available?
e.g. I want to check if overpower can be cast, if yes – cast it – if not – cast bloodthirst

**Comment by DennisWG** [comment]
There is no nice way of doing this. I can only check if an action on your action bar is usable which means that you'd have to put Overpower and the macro on your action bar. At this point, you might also just use Overpower as far as I'm concerned.

**Comment by moootv** [comment]
>  I can only check if an action on your action bar is usable which means that you'd have to put Overpower and the macro on your action bar

How can you do this? This would be sufficient.
