### ISSUE TITLE
Buff-Macro - Bug or am I missing something?

### ISSUE THREAD

**Issue by moootv** [DennisWG/CastModifier#21]
I use the following macro. Generally it works, but sometimes the Foodbuff (Smoked Desert Dumplings) will be used, even if I already have the “Well Fed” Buff.

/use [group:raid nomybuff:Juju_Power] Juju Power
/use [group:raid nomybuff:Juju_Might] Juju Might
/use [group:raid nomybuff:Elixir_of_the_Mongoose] Elixir of the Mongoose
/use [group:raid nomybuff:Well_Fed] Smoked Desert Dumplings

**Comment by DennisWG** [comment]
I can not reproduce this. I need more information on how this happens before I can try and fix this issue.

**Comment by moootv** [comment]
I noticed that it only appears to be in raids when already fullbuffed. Might be something have to do with buff limitations/overwriting buffs or not seeing that i already have this buff, when fullbuffed ?

**Comment by moootv** [comment]
Anyone got an idea?

**Comment by moootv** [comment]
Fixed the issue. Your addon is watching at 16 buffs, But the Buff limit is 32.

**Comment by DennisWG** [comment]
Thank you very much for figuring this out! A fix has been applied.
