### ISSUE TITLE
Multi-Shot issue

### ISSUE THREAD

**Issue by SuperNooby** [DennisWG/CastModifier#22]
I am not sure if it is something to do with the name, or the dash in it, but for some reason this simple macro: /cast [nocooldown:Multi-Shot] Multi-Shot does not work. It works fine with any other shots / hunter abilities that have a cooldown.

**Comment by SuperNooby** [comment]
Also, /cast Multi-Shot works fine, so it is something to do with the formatting within the nocooldown conditional?

**Comment by DennisWG** [comment]
Thank you for reporting this bug! I was able to fix it, so please make sure to re-download the newest version!
