### ISSUE TITLE
Mouseover on FocusFrame stop working.

### ISSUE THREAD

**Issue by vasecha** [DennisWG/CastModifier#23]
Hello Ike!
FocusFrame mouseover doesnt work with the last FocusFrame release: https://github.com/wardz/FocusFrame/releases/tag/v1.2.1
Could you PLEASE fix it?
Thank you in advance!

**Comment by DennisWG** [comment]
Hey!
I'm afraid FocusFrame works fine for me. Have you tried without any other Addons enabled to make sure there's nothing else that might be causing this problem? Also, did you get any error messages after logging in? Or does it just not work?

**Comment by vasecha** [comment]
Damnd voodoo magic... reinstalled both addons and its working now. Sooooory.
Thanks!

**Comment by DennisWG** [comment]
No worries I'm glad it's working!
