### ISSUE TITLE
[Request] Possibility of adding pet spells?

### ISSUE THREAD

**Issue by SuddenDeath** [DennisWG/CastModifier#3]
Instead of having to use macros such as this:

`/script TargetUnit("pet")`
`/script CastPetAction(2)`
`/script TargetLastTarget()`

would it be possible to make something like this work instead?

`/cast [@pet] Devour Magic`

or in any other way?

To cast pet spells you currently have to use the pet binds or `/script CastPetAction(x)`, the spell name with a regular "/cast" will not work.

**Comment by SuddenDeath** [comment]
Also things like

`/petattack [@focus]´

**Comment by DennisWG** [comment]
Hey,
unless I'm missing something, you can, in fact, cast Devour Magic via /cast command! Therefore `/cast [@pet] Devour Magic` works already (I've even tested this to make sure)!

The `/petattack` bit has been implemented, however! Very useful indeed. Thank you for the suggestion!
