### ISSUE TITLE
TargetLastTarget when using spells with myhp condition on self

### ISSUE THREAD

**Issue by Antonilz** [DennisWG/CastModifier#4]
For example this macro for warlock:
/cast [myhp<30] Life Tap(rank 1) ; Life Tap
Actually clears the target and targets last enemy on press and casts the spell as intended. Is it possible to not clear target, because it might be a little disturbing in the middle of the fight.

**Comment by Antonilz** [comment]
Well, it's not the myhp issue particularly, but the whole addon thingy. I'm also using classicFocus, may be it's the one causing issues. Reloading ui actually helps out.

**Comment by DennisWG** [comment]
I'll try to look into this as soon as I can!

**Comment by DennisWG** [comment]
I believe I've fixed this error. I'm not certain, though, as I was unable to reproduce it. If not feel free to re-open this issue (I think you're able to).
