### ISSUE TITLE
Allow combining multiple modifiers

### ISSUE THREAD

**Issue by DennisWG** [DennisWG/CastModifier#8]
e.g.
```
/cast [mod:alt/ctrl/shift] Healing Touch; [mod:alt/ctrl] Healing Touch(Rank 4): [mod:alt] Healing Touch(Rank 1)
```

**Comment by ettern** [comment]
Would it be possible to support multiple buff/debuff conditionals?
Eg. 
/cast [nodebuff:Taunt nodebuff:Mocking Blow nodebuff:Challenging Shout] Taunt;
/cast [nodebuff:Taunt nodebuff:Mocking Blow nodebuff:Challenging Shout] Mocking Blow;
/cast [nodebuff:Taunt nodebuff:Mocking Blow nodebuff:Challenging Shout] Challenging Shout;

**Comment by DennisWG** [comment]
I'll consider it when I look into this feature request.

**Comment by DennisWG** [comment]
Implemented.

**Comment by ettern** [comment]
Hi,
I still cant get this to work. Eg. I want to cast Taunt only if the target dont have Taunt, Mocking Blow or Challenging Shout debuff. Same goes for Mocking Blow and Challenging Shout.

Would it be possible to have eg. nodebuff accepting multiple debuffs (nodebuff:Taunt, Mocking Blow etc) and CastModifier would magically loop through all and check.
